# Generated by Django 4.2.13 on 2025-11-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0063_set_verbose_name_plural"),
    ]

    operations = [
        migrations.AddField(
            model_name="relayaddress",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="domainaddress",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
    ]
